name: Process Project Issue

on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to process"
        required: true

jobs:
  process-project:
    if: contains(github.event.label.name, 'approved') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      # ... your existing steps remain the same ...

      - name: Close issue with success message
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number || github.event.inputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Project successfully processed!** \n\nYour project submission has been processed and a pull request has been created. The project will be added to the directory once the PR is merged.\n\nThank you for your contribution! 🎉'
            });

            github.rest.issues.update({
              issue_number: ${{ github.event.issue.number || github.event.inputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              labels: ['processed', 'approved']
            });
